#!/usr/bin/env bash

# Abort this script if error happens
set -e

# Variable for implementation
CMD_NAME=`basename $0`
CUR_DIR=`pwd`

# Check whether the OS is macOS or not
if [ "$(uname)" != 'Darwin' ]; then
    echo "${CMD_NAME}: You can execute this command only on macOS." 1>&2
    exit 1
fi

# Parse specified options
FLAG_R=false
while getopts :rR OPT; do
    case $OPT in
        r)  FLAG_R=true;;
        R)  FLAG_R=true;;
        \?) echo "${CMD_NAME}: ${OPTARG}: Illegal option." 1>&2;
            exit 1;;
    esac
done

# Shift specified options
shift $((OPTIND - 1))

# Check the number of command line args
if [ "${#}" -lt 1 ]; then
    echo "Usage: ${CMD_NAME} [-r] <file>..." 1>&2
    exit 1
fi

# Move specified files / directories to the trash box
for NAME in ${*}; do
    # Don't remove "." and ".."
    if [ `basename "\\${NAME}"` == "." ] ||
       [ `basename "\\${NAME}"` == ".." ]; then
        echo "${CMD_NAME}: \".\" and \"..\" may not be removed." 1>&2
        continue
    fi
    # Check whether specified file / directory exists
    if [ ! -e ${NAME} ]; then
        echo "${CMD_NAME}: ${NAME}: No such file or directory." 1>&2
        continue
    fi
    # Require "-r" option when remove directory
    if [ -d ${NAME} -a ${FLAG_R} != true ]; then
        echo "${CMD_NAME}: ${NAME}: Require \"-r\" option when remove directory." 1>&2
        continue
    fi
    # Remove specified file / directory
    osascript -e """
    tell application \"Finder\"
        move POSIX file \"${CUR_DIR}/${NAME}\" to trash
    end tell
    """
done
